CREATE TABLE  
CUSTOMER
   (	CUST_CODE VARCHAR(6) NOT NULL PRIMARY KEY, 
	CUST_NAME VARCHAR(40) NOT NULL, 
	CUST_CITY CHAR(35), 
	WORKING_AREA VARCHAR(35) NOT NULL, 
	CUST_COUNTRY VARCHAR(20) NOT NULL, 
	GRADE decimal, 
	OPENING_AMT decimal(12,2) NOT NULL, 
	RECEIVE_AMT decimal(12,2) NOT NULL, 
	PAYMENT_AMT decimal(12,2) NOT NULL, 
	OUTSTANDING_AMT decimal(12,2) NOT NULL, 
	PHONE_NO VARCHAR(17) NOT NULL
);
